from harness import *
from playwright.sync_api import expect
import re,traceback
results=[];errors=[]
def check(name,condition,detail=''):
    results.append({'name':name,'passed':bool(condition),'detail':detail})
    print('PASS' if condition else 'FAIL',name,detail[:120],flush=True)
    (OUT/'browser-progress.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
def no_han(text):return re.search(r'[\u4e00-\u9fff]',text.replace('中文','')) is None
def draft(pg):return pg.evaluate("window.__databases?.['dlcj-drafts']?.drafts?.records?.current")
def close(pg):pg.keyboard.press('Escape');pg.wait_for_timeout(180)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_BINARY'),headless=True,args=['--no-sandbox'])
    def page(path,width=390):
        pg=b.new_page(viewport={'width':width,'height':844 if width<600 else 1000});pg.set_default_timeout(5000);pg.emulate_media(reduced_motion='reduce');pg.route(ORIGIN+'/**',route);pg.on('pageerror',lambda e:errors.append(str(e)));render(pg,path);return pg
    pg=page('/?lang=en',1440)
    check('English homepage UI',no_han(pg.locator('body').inner_text()))
    links=pg.locator('a[href*="/customize"]').evaluate_all('(es)=>es.map(e=>e.getAttribute("href"))')
    check('Every homepage studio link carries English',len(links)>5 and all('lang=en' in x for x in links),str(links))
    check('All original preset thumbnails loaded',pg.locator('.colourway-image img').evaluate_all('(es)=>es.length===3 && es.every(e=>e.complete&&e.naturalWidth>0)'))
    requested=pg.evaluate('performance.getEntriesByType("resource").map(e=>e.name)')
    check('Homepage does not load 3D runtime or model',not any('studio-BSb' in x or x.endswith('.glb') for x in requested))
    for width in [320,360,390,430,768,1024,1440]:
        pg.set_viewport_size({'width':width,'height':844});pg.wait_for_timeout(80)
        check(f'Homepage fits {width}px',pg.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    pg.set_viewport_size({'width':1440,'height':1000});pg.screenshot(path=str(OUT/'home-desktop-en.png'),full_page=True)
    pg.locator('details').first.locator('summary').click();check('Product details expand on demand',pg.locator('details').first.get_attribute('open') is not None)
    pg.close()
    pg=page('/customize?lang=en&preview=light',1440)
    check('Entire initial studio UI English',no_han(pg.locator('body').inner_text()))
    for width in [320,360,390,430,768,1024,1440]:
        pg.set_viewport_size({'width':width,'height':844});pg.wait_for_timeout(80)
        check(f'Studio fits {width}px',pg.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if width<600:
            visible=pg.locator('[data-preset]').evaluate_all('(es)=>es.length===3&&es.every(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight})')
            check(f'All three presets visible in first screen at {width}px',visible)
    pg.set_viewport_size({'width':390,'height':844})
    pg.screenshot(path=str(OUT/'studio-mobile-en.png'),full_page=True)
    pg.locator('[data-preset="black-coral"]').click();pg.wait_for_timeout(500)
    check('Second card applies original black/coral design',draft(pg)['parts']['body']['color']=='#273137')
    pg.locator('[data-preset="forest-linen"]').click();expect(pg.get_by_role('dialog')).to_be_visible()
    check('Replacing an edited/preset design asks confirmation',True)
    apply=pg.get_by_role('dialog').locator('button').filter(has_text=re.compile('Apply'))
    apply.click();pg.wait_for_timeout(500)
    check('Third card applies original forest/linen side label',draft(pg)['parts']['body']['color']=='#365d52' and draft(pg)['label']['enabled'])
    pg.get_by_role('button',name='Undo',exact=True).click();pg.wait_for_timeout(500)
    check('Preset replacement can be undone',draft(pg)['parts']['body']['color']=='#273137')
    pg.get_by_role('button',name='Save design',exact=True).click();check('English preset name in editable save field',pg.locator('#designName').input_value()=='Obsidian · Coral')
    pg.locator('#designName').fill('');check('Empty design name cannot be saved',pg.get_by_role('button',name='Save in this browser',exact=True).is_disabled())
    close(pg);check('Cancelling empty name preserves existing design',draft(pg)['name']=='曜石 · 珊瑚红')
    pg.get_by_role('button',name='Save design',exact=True).click();pg.locator('#designName').fill('My personal design');pg.get_by_role('button',name='Save in this browser',exact=True).click();pg.wait_for_timeout(500);check('Named design stored through original IDB code with test backend',draft(pg)['name']=='My personal design');close(pg)
    pg.get_by_role('button',name='My designs',exact=True).click();expect(pg.get_by_role('dialog').get_by_text('My personal design',exact=True)).to_be_visible();check('Saved library lists named design',pg.get_by_role('dialog').get_by_text('My personal design',exact=True).is_visible());pg.get_by_role('dialog').get_by_role('button',name=re.compile('My personal design')).click();pg.wait_for_timeout(250);check('Library reopen restores the current design',pg.get_by_role('dialog').count()==0)
    pg.get_by_role('tab',name='Artwork',exact=True).click();pg.get_by_role('textbox',name='Artwork text',exact=True).fill('Hello 你好');pg.get_by_role('button',name='Add text',exact=True).click();pg.wait_for_timeout(500)
    check('User authored Chinese/English text is preserved',draft(pg)['parts']['body']['art'][0]['text']=='Hello 你好')
    pg.get_by_role('button',name='Review & enquire',exact=True).click();dlg=pg.get_by_role('dialog')
    check('Consultation contacts and fields use English',dlg.get_by_role('button',name='Copy WeChat ID',exact=True).count()==1 and not re.search(r'电话咨询|微信咨询|复制微信号',dlg.inner_text()))
    dlg.locator('#consultQuantity').fill('0');check('Invalid quantity disables enquiry copy',dlg.get_by_role('button',name='Copy enquiry',exact=True).is_disabled())
    dlg.locator('#consultQuantity').fill('2');dlg.locator('#consultNote').fill('Please quote two pieces.');check('Valid quantity enables enquiry copy',dlg.get_by_role('button',name='Copy enquiry',exact=True).is_enabled())
    dlg.get_by_role('button',name='Copy enquiry',exact=True).click();pg.wait_for_timeout(150)
    check('Clipboard unavailable exposes manual-copy textbox',dlg.locator('textarea[readonly]').count()>0)
    pg.screenshot(path=str(OUT/'consult-mobile-en.png'),full_page=True)
    txt=dlg.locator('textarea[readonly]').input_value();check('Manual-copy text retains custom artwork and quantity','Hello 你好' in txt and '2' in txt)
    close(pg);pg.get_by_role('button',name='Review & enquire',exact=True).click();check('Notes survive closing and reopening enquiry',pg.locator('#consultNote').input_value()=='Please quote two pieces.');close(pg)
    pg.get_by_role('link',name='Back to collection',exact=True).click();pg.wait_for_timeout(150)
    check('Back saves latest draft and targets English homepage',pg.evaluate('window.__lastNavigation')==ORIGIN+'/?lang=en' and draft(pg)['parts']['body']['art'][0]['text']=='Hello 你好')
    pg.locator('.language-switch a[lang="zh-CN"]').click();pg.wait_for_timeout(150)
    check('Language switch preserves route and light-preview flag','/customize?' in pg.evaluate('window.__lastNavigation') and 'lang=zh' in pg.evaluate('window.__lastNavigation') and 'preview=light' in pg.evaluate('window.__lastNavigation'))
    pg.close()
    pg=page('/customize?lang=en&preview=light&preset=forest-linen')
    check('Direct preset deep link applies real design',draft(pg)['parts']['body']['color']=='#365d52')
    check('Consumed preset removed from URL to prevent reapplying on refresh','preset=' not in pg.evaluate('window.__testLocation.search'))
    pg.evaluate('window.__storageDenied=true');pg.get_by_role('button',name='Leather colour: Pearl white').count() if False else None
    pg.get_by_role('link',name='Back to collection',exact=True).click();pg.wait_for_timeout(150)
    check('Storage failure opens export/leave guard',pg.get_by_role('dialog').get_by_text('Keep your design before leaving',exact=True).is_visible())
    pg.get_by_role('button',name='Leave anyway',exact=True).click();pg.wait_for_timeout(150)
    check('Storage failure does not trap user on page',pg.evaluate('window.__lastNavigation')==ORIGIN+'/?lang=en');pg.close()
    pg=page('/customize?lang=en')
    check('Unavailable WebGL shows localized fallback',pg.get_by_text('3D is unavailable in this browser.',exact=True).is_visible())
    check('Camera controls are disabled without a model',pg.get_by_role('button',name='Zoom in',exact=True).is_disabled())
    pg.get_by_role('button',name='Export design',exact=True).click()
    check('PNG export disabled but JSON remains available without 3D',pg.get_by_role('button',name=re.compile('Multi-view preview')).is_disabled() and pg.get_by_role('button',name=re.compile('Editable design file')).is_enabled())
    pg.close()
    check('No uncaught JavaScript errors in tested application flows',len(errors)==0,str(errors))
    b.close()
(OUT/'browser-results.json').write_text(json.dumps({'mode':'Chromium embedded document; simulated URL navigation + localStorage + IndexedDB backend. Original application modules and DOM run unchanged except browser-boundary substitution. WebGL unavailable.','passed':sum(x['passed'] for x in results),'total':len(results),'cases':results},indent=2,ensure_ascii=False))

raise SystemExit(0 if all(case['passed'] for case in results) else 1)
